# golangci-lint configuration
# https://github.com/golangci/golangci/wiki/Configuration

linters:
  enable:
    - goimports

service:
  golangci-lint-version: 1.39.x # use the fixed version to not introduce new linters unexpectedly
#  prepare:
#    - echo "here I can run custom commands, but no preparation needed for this repo"
