name: test
on: 
  push:
    branches-ignore:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test Command
      run: |
        echo $QUAY_USER
        echo $QUAY_PASSWD
        echo $GITHUB_TOKEN
